### ISSUE TITLE
incorrect boolean test?

### ISSUE THREAD

**Issue by danielweck** [Heydon/watched-box#1]
https://github.com/Heydon/watched-box/blob/f45b9227d49af1bfbef20aa7610dd314f113dfa3/watched-box.js#L115

shouldn’t this be `&&`?

**Comment by Heydon** [comment]
@danielweck Yep, you're quite right. Not sure what the heck I did there. Fixed in the patch: https://github.com/Heydon/watched-box/releases/tag/0.1.1
