### ISSUE TITLE
It's too simple and good

### ISSUE THREAD

**Issue by argyleink** [Heydon/watched-box#3]
It's not confusing or bloated enough, please add complexity.

Also, the code was too easy to read, less comments, helpful meta and feature checking. Should be hard to use. Where's the webpack config getting started section?

**Comment by Heydon** [comment]
@argyleink Haha. I did wonder which packager managers I might support? I tried publishing to npm but there seemed to be a caching issue after I changed my password. I'll try again today.

**Comment by argyleink** [comment]
i was kidding, no feature requests, just kudos. rad work yo.
